use cookie on server too (instead of event.context)
becem-gharbi/nuxt-directus pull request #50
Opened 2023-08-29 19:08 UTC by Dominic-Marcelino

Currently the module uses the event-context the server to store the access token. This leads to a lost token on a full page-reload. The problem should be solved by always relying on the cookie.

Looking forward to your feedback.

2023-08-29 20:12 UTC, becem-gharbi commented
Yes, I already have this issue in backlog. I planned to fix it on future release.

2023-08-29 20:17 UTC, becem-gharbi requested changes
The access token should first be checked on `event.context` then on cookie storage.
```js
 process.server ? 
  event.context[accessTokenCookieName] || getCookie(event, accessTokenCookieName) 
  : useCookie(accessTokenCookieName).value
```

2023-08-30 08:47 UTC, Dominic-Marcelino commented
> The access token should first be checked on `event.context` then on cookie storage.
> 
> ```js
>  process.server ? 
>   event.context[accessTokenCookieName] || getCookie(event, accessTokenCookieName) 
>   : useCookie(accessTokenCookieName).value
> ```

Out of curiosity: 
1. What's the reason to duplicate the token into the event?
2. What's the benefit of usings h3's `getCookie()` instead of Nuxts already SSR friendly `useCookie()`

2023-08-30 09:53 UTC, becem-gharbi commented
Hi, the reason I don't use `useCookie` on server-side is because it's not reliable. So I tend to always use `h3` apis on server-side whenever possible. You can try to run this server plugin and check the behaviour
```js
export default defineNuxtPlugin(() => {
  useCookie("test").value = "on"; // Update
  console.log(useCookie("test").value); // Read
  useCookie("test").value = null; // Delete
});

```

2023-08-31 12:44 UTC, closed without merging

2023-08-31 12:58 UTC, Dominic-Marcelino commented
Was automatically closed, as this was accidentially created from main. Will re-open it from a new branch

2023-08-31 21:53 UTC, becem-gharbi commented
Before moving on to the new PR, what is your view on my previous comment?

2023-09-01 07:39 UTC, Dominic-Marcelino commented
> Before moving on to the new PR, what is your view on my previous comment?

What's the reason to duplicate the token into the event.context? I think we can ditch this duplication.

If it's not needed anymore, I personally wouldn't add another differentiation between client & server, as `useCookie` is designed by nutzt to work on both (even if it doesn't have dedicated methods as mentioned in your previous comment). If you prefer thizgh, it's still possible of course.

2023-09-01 08:03 UTC, becem-gharbi commented
Have you tested the plugin? Did it work as expected?

2023-09-01 08:11 UTC, Dominic-Marcelino commented
In my manually performed tests everything worked as expected 👍🏼

2023-09-01 08:16 UTC, becem-gharbi commented
In my case it's messed up, the cookie value is undefined and the cookie is not deleted, I wonder why? By the way I'm using windows.

2023-09-01 08:53 UTC, Dominic-Marcelino commented
When exactly are you getting the error? 
I've tested it on Chrome + Firefox without any problems (Mac) in ssr + csr. When logging in the cookie is read and on log-out the cookie is deleted. 
On safari the login-cookie will never be set, but I assume that's some kind of safari local-dev-burden again 😅

2023-09-01 08:58 UTC, becem-gharbi commented
In such case I would take the safe choice, use `h3` apis for handling cookies and `event.context` to share the value on server-side.